DESCRIPTION

XDCR verification cleanup - renaming, ignoring checks, cancelling failed item count tasks

Change-Id: I9c9ef60739412e5fbc770eb0e8c8311dd9a82002


COMMENTS

author: Angelina Mayer
date: 2014-05-14 05:30:54.365000000

Uploaded patch set 3.

-------------------------------------
author: Hugo Blankenship
date: 2014-05-14 05:30:59.633000000

Patch Set 3:

Build Started http://factory.couchbase.com/job/testrunner-Jasmin Rangel-master/1425/

-------------------------------------
author: Hugo Blankenship
date: 2014-05-14 05:58:46.322000000

Patch Set 3: Verified-1

Build Failed 

http://factory.couchbase.com/job/testrunner-Jasmin Rangel-master/1425/ : FAILURE

detect lines like:

suite viewmergetests.ViewMergingTests , pass 38 , fail 1

-------------------------------------
author: Fisher Vargas
date: 2014-05-14 06:29:11.183000000

Patch Set 3: Code-Review-1

(5 comments)

Line:378, pytests/xdcr/pauseResumeXDCR.py -> I think this argument were passed in case any topology change on source side. any reason to remove it.

Line:1251, pytests/xdcr/xdcrbasetests.py -> behavior of function will change.

Line:1289, pytests/xdcr/xdcrbasetests.py -> return statement has no effect. Please remove.

Line:1297, pytests/xdcr/xdcrbasetests.py -> ValueError is builtin type exception, please use XdcrException instead.

Line:1141, lib/tasks/task.py -> This check should move outside if statement. Otherwise it will be printed each time.

-------------------------------------
author: Esperanza Cherry
date: 2014-05-14 09:53:23.109000000

Patch Set 3:

(1 comment)

Line:1141, lib/tasks/task.py -> for me it will be printed only once

-------------------------------------
author: Angelina Mayer
date: 2014-05-14 16:59:04.583000000

Patch Set 3:

(5 comments)

Line:378, pytests/xdcr/pauseResumeXDCR.py -> Because I think we should verify source items in any XDCR test without a choice. MB-10856 was one case (no topology changes) where only items at dest were checked while the items at source did not match the value expected. And testrunner did not catch it.

Line:1251, pytests/xdcr/xdcrbasetests.py -> in future you mean?

Line:1289, pytests/xdcr/xdcrbasetests.py -> We return true when there are no exceptions, false when there are.

Line:1297, pytests/xdcr/xdcrbasetests.py -> Ok

Line:1141, lib/tasks/task.py -> It gets printed only once when this condition is met. I've tested this.

-------------------------------------
author: Tate Garrett
date: 2014-05-15 03:43:16.101000000

The change could not be merged due to a path conflict.

Please rebase the change locally and upload the rebased commit for review.

-------------------------------------
