DESCRIPTION

CBQE-175 Rebalance Tests for Create Views

Change-Id: Ie871b057c12755ea49b3b3e1bf0e403aaf2babf2


COMMENTS

author: Maliyah Fischer
date: 2012-06-20 05:39:03.928000000

Uploaded patch set 2.

-------------------------------------
author: Hugo Blankenship
date: 2012-06-20 05:39:07.379000000

Patch Set 2:

Build Started http://qa.hq.northscale.net/job/testrunner-Jasmin Rangel-master/1068/ 

-------------------------------------
author: Hugo Blankenship
date: 2012-06-20 05:48:40.770000000

Patch Set 2: Verified

Build Successful 

http://qa.hq.northscale.net/job/testrunner-Jasmin Rangel-master/1068/ : SUCCESS

-------------------------------------
author: Esperanza Cherry
date: 2012-06-20 17:58:41.626000000

Patch Set 2: I would prefer that you didn't submit this

(6 inline comments)

code looks much better, but execution results are not stable and i see errors like as: 

ERROR - http://10.5.2.11:8091/couchBase/default/_design/dev_ddoc1/_view/default_view2?stale=ok error 500 reason: error {"error":"error","reason":"revision_sync_failed"}

http://10.5.2.11:8091/couchBase/default/_design/dev_ddoc0/_view/default_view1?stale=ok error 500 reason: error {"error":"error","reason":"revision_sync_failed"}

What is the reason?

Line:38, pytests/view/createviewtests.py -> kv_stores is not needed here

Line:96, pytests/view/createviewtests.py -> I guess the logic can be simple. So it is better to call the variables so that you can determine where the expected result, where the actual

Line:105, pytests/view/createviewtests.py -> test should be failed here?

Line:108, pytests/view/createviewtests.py -> why only info message? when it is failed?

Line:1, conf/py-createview.conf -> colon at the end of the class name:
view.createviewtests.CreateDDocTests:

Line:6, conf/py-createview.conf -> colon

-------------------------------------
