DESCRIPTION

Bug 1629: Retry rebalance on abnormal exit.

This turns this:

Rebalance exited with reason {{{badmatch,{error,closed}},
[{mc_client_binary,cmd_binary_vocal,5}, {mc_client_binary,stats,2},
{ns_memcached,handle_call,3}, {gen_server,handle_msg,5},
{proc_lib,init_p_do_apply,3}]}, {gen_server,call,
xxx@xxx.xxx {stats,"default","vbucket"}]}}

into this:

ERROR REPORT  <5608.502.0>                                  2010-06-29 10:49:08
===============================================================================

Rebalance received exit: {{{badmatch,{error,closed}},
                           [{mc_client_binary,stats_recv,3},
                            {mc_client_binary,stats,2},
                            {ns_memcached,handle_call,3},
                            {gen_server,handle_msg,5},
                            {proc_lib,init_p_do_apply,3}]},
                          {gen_server,call,
                                      xxx@xxx.xxx
                                       {stats,"default","vbucket"}]}}, retrying.

I tested this with "killall -9 memcached" in the middle of the rebalance.

We'll retry up to twice right now, with a 1500ms sleep in between.

Change-Id: I56e9d0d89a332560642b21181b59c5b017338c10


COMMENTS

author: Nora Conway
date: 2010-06-29 18:57:09.485000000

Patch Set 1: Looks good to me, approved



-------------------------------------
author: Nora Conway
date: 2010-06-29 19:00:55.190000000

Patch Set 1: Verified



-------------------------------------
author: Nora Conway
date: 2010-06-29 19:00:55.390000000

Change has been successfully cherry-picked as 0b00379632858eaa4dbcae21a7fff4c43c3304e0.

-------------------------------------
