DESCRIPTION

CBQE-0 : observe tests don't run teardown if setup failed

Change-Id: I8b3d0df682989f9074c69efb43f0a221266730a4


COMMENTS

author: Moises Brennan
date: 2014-06-10 10:36:50.689000000

Uploaded patch set 2.

-------------------------------------
author: Hugo Blankenship
date: 2014-06-10 10:36:56.531000000

Patch Set 2:

Build Started http://factory.couchbase.com/job/testrunner-Jasmin Rangel-master/1691/

-------------------------------------
author: Hugo Blankenship
date: 2014-06-10 10:56:44.088000000

Patch Set 2: Verified+1

Build Successful 

http://factory.couchbase.com/job/testrunner-Jasmin Rangel-master/1691/ : SUCCESS

-------------------------------------
author: Esperanza Cherry
date: 2014-06-10 11:14:33.331000000

Patch Set 2: Code-Review+2

(1 comment)

Line:29, pytests/observe/observetest.py -> I think you should add in try-catch only for step 'self.cluster.rebalance" because "super(ObserveTests, self).setUp()" already handles it

-------------------------------------
author: Esperanza Cherry
date: 2014-06-10 11:14:40.176000000

Patch Set 2: -Code-Review

-------------------------------------
author: Moises Brennan
date: 2014-06-10 11:21:32.655000000

Patch Set 2:

(1 comment)

Line:29, pytests/observe/observetest.py -> As far as observed http://qa.hq.northscale.net/job/centos_x64--44_04--observe-P0/34/consoleFull it's in setup which before rebalance as bucket creation is itself not successful because it wasn't deleted in previous test as tearDown doesn't run.

-------------------------------------
